###
GET http://localhost:3000/actors

###
GET http://localhost:3000/actors/673f7636d35d232ed759713c

###
POST  http://localhost:3000/actors/search
Content-Type: application/json

{
    "seasons": [17]
}

###
POST http://localhost:3000/actors/search
Content-Type: application/json

{
    "character": "Shepherd"
}

###
POST http://localhost:3000/actors/search
Content-Type: application/json

{
    "gender": "female"
}

###
POST http://localhost:3000/actors
Content-Type: application/json

{
    "firstName": "Chyler",
    "lastName": "Leigh",
    "gender": "female",
    "character": "Lexie Grey",
    "firstAppearSeason": 3,
    "seasons": [3,4,5,6,7,8,17]
}

###
PUT  http://localhost:3000/actors/673f7636d35d232ed759713c
Content-Type: application/json

{
    "firstName": "Any",
    "lastName": "Any",
    "gender": "female",
    "character": "Any Character",
    "firstAppearSeason": 3,
    "seasons": [3,4,5,6,7,8,17]
}

###
DELETE http://localhost:3000/actors/673f7636d35d232ed759713c

###
DELETE http://localhost:3000/actors