###
GET http://localhost:3000/actors

###
GET http://localhost:3000/actors/673e22bc1907ab65af95ec30

###
POST  http://localhost:3000/actors/search
Content-Type: application/json

{
    "seasons": [1]
}

###
POST http://localhost:3000/actors/search
Content-Type: application/json

{
    "character": "Shepherd"
}

###
POST http://localhost:3000/actors/search
Content-Type: application/json

{
    "gender": "female"
}

###
POST http://localhost:3000/actors
Content-Type: application/json

{
    "firstName": "Chyler",
    "lastName": "Leigh",
    "gender": "female",
    "character": "Lexie Grey",
    "firstAppear": 3,
    "seasons": [3,4,5,6,7,8,17]
}

###
PATCH  http://localhost:3000/actors/673e22bc1907ab65af95ec30
Content-Type: application/json

{
    "gender": "others"
}

###
DELETE http://localhost:3000/actors/673e22bc1907ab65af95ec30

###
DELETE http://localhost:3000/actors